services:
  forum:
    container_name: forum
    build: ./forum
    command: bash -c "python ./manage.py makemigrations --noinput && python ./manage.py migrate --noinput && python ./manage.py collectstatic --noinput && python ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    ports:
      - 80:80 # Nginx 外部端口80（http默认端口），内部端口80
    depends_on:
      - forum
  db:
    container_name: postgres
    image: postgres:15
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.env

volumes:
  media_volume:
  static_volume:
  postgres_volume: