# Generated by Django 4.2 on 2023-06-13 16:49

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', martor.models.MartorField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_comments', to='articles.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_comments', to='accounts.account')),
                ('downvotes', models.ManyToManyField(blank=True, related_name='downvote_comments', to='accounts.account')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvote_comments', to='accounts.account')),
            ],
        ),
    ]
