# Generated by Django 4.2 on 2023-06-13 16:49

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('content', martor.models.MartorField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_articles', to='accounts.account')),
                ('downvotes', models.ManyToManyField(blank=True, related_name='downvote_articles', to='accounts.account')),
                ('upvotes', models.ManyToManyField(blank=True, related_name='upvote_articles', to='accounts.account')),
            ],
        ),
    ]
