# Generated by Django 4.2 on 2023-06-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='follower', to='accounts.account'),
        ),
    ]
