# Generated by Django 4.2 on 2023-06-10 18:30

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
